### ISSUE TITLE
Sales Report does not update to sales made to the same Site with a different device

### ISSUE THREAD

**Issue by marcmalone** [untapped-inc/sema-core-archived#40]
I have 2 devices logged in to the same Site with the same username and password. If I make a sale on one device, it shows up on the Sales Log of the 2nd device and adjust the customer credit on the 2nd device, but it does not show up on the Sales Report or Inventory Report of the 2nd device.

**Comment by meaudotme** [comment]
This is by design. The sales and inventory reports only reflect sales made during the day for the tablet. This data is not uploaded to the server, which is why it's not synchronized.

One thing to keep in mind is that the POS app was not meant to be used on multiple devices at the same kiosk. Only one device per kiosk.

This is essentially a feature request.

**Comment by marcmalone** [comment]
Thanks Nick. The tricky thing is that the Saleslog *does *cross-sync to a
2nd device at the same kiosk, which makes the fact that the Sales Report
does not cross-sync more confusing. I am fine with considering this a
feature request and addressing at a later date.

*Marc Malone | Chief Engineer **|** marc.malone@jibuco.com
<marc.malone@jibuco.com>*

*+250.780.660.617 <(250)%780660617>** | Skype: marc.malone1 | Time zone:
CAT (Rwanda)*

*Jibu* <http://jibuco.com/>* | Local owners driving lasting solutions*

*We are HIRING! See **current opportunity by clicking here
<https://jibuco.com/jobs/>.*

**Comment by meaudotme** [comment]
I see. The sales log tool is not cross syncing, it's just that you switched to another site through the settings screen but the logged sales don't get cleared. Will attach a commit that fixes this issue. Thank you.
